import type { MetadataRoute } from "next";
import { localePrefixMap } from '@/middleware'; // Ensure this path is correct

// This file generates the sitemap index for the website.
// It points to individual sitemap files generated for each locale.
// Individual sitemaps are generated by: app/sitemaps/[locale]/route.ts

// Base URL from environment variable
const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://xiangleratchetstrap.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const sitemapEntries: MetadataRoute.Sitemap = [];

  // Add one sitemap per locale
  // Assuming localePrefixMap's values are the locale codes like 'en', 'zh'
  for (const locale of Object.values(localePrefixMap)) {
    sitemapEntries.push({
      // The path should match your dynamic route in app/sitemaps/[locale]/route.ts
      url: `${BASE_URL}/sitemaps/${locale}`,
      lastModified: new Date(),
    });
  }

  return sitemapEntries;
}
